version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: veloz
      POSTGRES_PASSWORD: veloz123
      POSTGRES_DB: pedidos
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - veloz-net

  pedidos:
    build: ./services/pedidos
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    networks:
      - veloz-net

  pagamentos:
    build: ./services/pagamentos
    ports:
      - "3002:3000"
    networks:
      - veloz-net

  estoque:
    build: ./services/estoque
    ports:
      - "3003:3000"
    networks:
      - veloz-net

  api-gateway:
    build: ./services/api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - pedidos
      - pagamentos
      - estoque
    networks:
      - veloz-net

volumes:
  pgdata:

networks:
  veloz-net:
